"""empty message

Revision ID: 0a2465a2e00d
Revises: e9a89289e1ac
Create Date: 2023-06-19 18:12:11.722029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a2465a2e00d'
down_revision = 'e9a89289e1ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asociacion', schema=None) as batch_op:
        batch_op.alter_column('asociacion_image',
               existing_type=sa.VARCHAR(length=550),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asociacion', schema=None) as batch_op:
        batch_op.alter_column('asociacion_image',
               existing_type=sa.VARCHAR(length=550),
               nullable=False)

    # ### end Alembic commands ###
