"""empty message

Revision ID: 40a636562f7a
Revises: ea00a4d713ac
Create Date: 2023-05-25 22:40:49.145682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40a636562f7a'
down_revision = 'ea00a4d713ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adoption', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False))
        batch_op.drop_column('submited_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adoption', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submited_date', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.drop_column('date')

    # ### end Alembic commands ###
