"""empty message

Revision ID: 415061e348a4
Revises: 5cee56470d17
Create Date: 2023-05-29 18:24:35.903003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '415061e348a4'
down_revision = '5cee56470d17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asociacion_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'asociacion', ['asociacion_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('asociacion_id')

    # ### end Alembic commands ###
