"""empty message

Revision ID: 4db39caaae3b
Revises: 44648f4d4163
Create Date: 2023-06-02 18:49:11.065243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4db39caaae3b'
down_revision = '44648f4d4163'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=True))
        batch_op.drop_column('insertion_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('insertion_date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.drop_column('date')

    # ### end Alembic commands ###
