"""empty message

Revision ID: 570018597d2f
Revises: 
Create Date: 2023-06-21 14:08:00.250345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '570018597d2f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asociacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('provincia', sa.String(length=80), nullable=False),
    sa.Column('CIF', sa.String(length=80), nullable=False),
    sa.Column('descripcion', sa.String(length=180), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('asociacion_image', sa.String(length=550), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asociacion_image')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('apellido', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('animal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('tipo_animal', sa.String(length=50), nullable=False),
    sa.Column('raza', sa.String(length=80), nullable=False),
    sa.Column('edad', sa.String(length=50), nullable=False),
    sa.Column('genero', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('asociacion_id', sa.Integer(), nullable=False),
    sa.Column('animal_image', sa.String(length=550), nullable=False),
    sa.ForeignKeyConstraint(['asociacion_id'], ['asociacion.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('animal_image')
    )
    op.create_table('adoption',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('asociacion_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], ),
    sa.ForeignKeyConstraint(['asociacion_id'], ['asociacion.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite')
    op.drop_table('adoption')
    op.drop_table('animal')
    op.drop_table('user')
    op.drop_table('asociacion')
    # ### end Alembic commands ###
