"""empty message

Revision ID: 5cb7d6c7f09f
Revises: e70d32110b56
Create Date: 2023-06-06 18:07:47.494995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cb7d6c7f09f'
down_revision = 'e70d32110b56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('chus')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chus', sa.VARCHAR(length=80), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
