"""empty message

Revision ID: 63914d326fbf
Revises: 
Create Date: 2023-06-07 18:38:03.805319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63914d326fbf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=False))

    with op.batch_alter_table('asociacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=False))

    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=True))
        batch_op.drop_column('insertion_date')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('chus')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chus', sa.VARCHAR(length=80), autoincrement=False, nullable=False))

    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('insertion_date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.drop_column('date')

    with op.batch_alter_table('asociacion', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
