"""empty message

Revision ID: 7ce564088942
Revises: 4db39caaae3b
Create Date: 2023-06-02 18:52:45.417958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ce564088942'
down_revision = '4db39caaae3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=False))

    with op.batch_alter_table('asociacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    with op.batch_alter_table('asociacion', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
