"""empty message

Revision ID: 9399f92c201c
Revises: 44717992b0eb
Create Date: 2023-06-05 16:17:13.124646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9399f92c201c'
down_revision = '44717992b0eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asociacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asociacion', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
