"""empty message

Revision ID: 9876cc271fd1
Revises: 4a61e1386c60
Create Date: 2023-05-25 02:32:36.335104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9876cc271fd1'
down_revision = '4a61e1386c60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('raza', sa.String(length=80), nullable=False),
    sa.Column('edad', sa.String(length=50), nullable=False),
    sa.Column('genero', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('animal')
    # ### end Alembic commands ###
